export const Users = [
  {
    id:1,
    profilePicture: "assets/person/profile-pic.png",
    username: "Gian Brunner",
  },
  {
    id:2,
    profilePicture: "assets/person/profile-pic.png",
    username: "Gian Brunner",
  },
  {
    id:3,
    profilePicture: "assets/person/profile-pic-m.jpeg",
    username: "Marti Manzo",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Andrés Ceballos",
  },
  {
    id:5,
    profilePicture: "assets/person/profile-pic.png",
    username: "Gian Brunner",
  },
  {
    id:6,
    profilePicture: "assets/person/profile-pic-m.jpeg",
    username: "Marti Manzo",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "María Gutierrez",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Cristian Rodriguez",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Carla Fernandez",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Ernesto Durán",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Buenas! Estoy en busqueda activa como Front End Developer, actualmente soy tutor del curso de Desarrollo Web en Coderhouse. Dejo mi correo para quien quiera contactarse: gianbrunner1@gmail.com",
    photo: "assets/post/cv.png",
    date: "Hace 5 minutos",
    userId: 1,
    like: 324,
    comment: 249,
  },
  {
    id: 2,
    desc: "@Marti mi fotografa favorita.",
    photo: "assets/post/building.jpg",
    date: "Hace 15 minutos",
    userId: 2,
    like: 2002,
    comment: 1506,
  },
  {
    id: 3,
    desc: "2 de junio, 2021. Rosa y amarillo.",
    photo: "assets/post/pot.jpg",
    date: "Hace 1 hora",
    userId: 3,
    like: 2108,
    comment: 1997,
  },
  {
    id: 4,
    desc: "Lorem ipsum dolor sit amet consectetur adipiscing, elit dictumst auctor semper tortor.",
    date: "Hace 4 horas",
    userId: 4,
    like: 531,
    comment: 324,
  },
  {
    id: 5,
    desc: "Terminé la carrera de Desarrollo Front End en Coderhouse!",
    photo: "assets/post/certificate.jpg",
    date: "Hace 5 horas",
    userId: 5,
    like: 743,
    comment: 443,
  },
  {
    id: 6,
    desc: "Our flowers.",
    photo: "assets/post/our-flowers.jpg",
    date: "Hace 1 día",
    userId: 6,
    like: 2018,
    comment: 807,
  },
  {
    id: 7,
    desc: "Lorem ipsum dolor sit amet consectetur adipiscing, elit augue ad interdum.",
    photo: "assets/post/house.jpg",
    date: "Hace 2 días",
    userId: 7,
    like: 522,
    comment: 345,
  },
  {
    id: 8,
    photo: "assets/post/cat.jpg",
    date: "Hace 3 días",
    userId: 8,
    like: 1124,
    comment: 143,
  },
  {
    id: 9,
    desc: "Lorem ipsum dolor sit amet consectetur, adipiscing elit neque ridiculus.",
    photo: "assets/post/tree.jpg",
    date: "Hace 5 días",
    userId: 9,
    like: 112,
    comment: 24,
  },
  {
    id: 10,
    photo: "assets/post/cloud.jpg",
    date: "Hace 1 semana",
    userId: 10,
    like: 1024,
    comment: 124,
  },
];
